calmato/gran

container/client/Dockerfile, docker-compose.yml
=> nuxtのdocker fileの作成

.dependabot/config.yml
初めて書いたから動くかはわからん...
動かんかったらマージ後修正したプルリク出すかも!!
以下、URLを参考に作成しました
> [dependabotの公式Doc](https://dependabot.com/docs/config-file/)
=> dependabotの設定

.github/workflows/client-ci.yml
GItHub Actionsのpathsを修正したので確認お願いします🙏
=> fix: clinet/**に修正

.github/workflows/user-api-ci.yml, api/user/Makefile
=> feature: API (User Service) の Github Actionsを作成

.env.sample, container/proxy/Dockerfile, container/proxy/envoy_dev.yaml, docker-compose.yml
ただ単に使ってみたかったって理由で、NginxではなくEnvoyでProxyサーバを実装しました。
実装内容は、[公式リファレンス](https://www.envoyproxy.io/docs/envoy/latest/about_docs)を参考にしました。
Client側から送ってくるHeaderの値?をまだ決めてなかったので、Corsの設定については後ほど修正するかもです🙇‍♂️
=> feature: コンテナ用Proxyサーバ設定

.github/workflows/client-lighthouse-ci.yml, client/lighthouserc.json
GitHub ActionsにLighthouseを追加した．
またこのリポジトリにLighthouse ciのGitHub Appを導入した．
大体の設定は以下のサイトを参考にした．
https://tech.smartshopping.co.jp/Lighthouse%20CI
おそらく無い
<hr>
pull request時のみで動かしたいので別ファイルで切り出したが，cdの設定に組み込んでも良いかも🤔
=> feat: GitHub ActionsにLighthouseを追加

api/user/internal/interface/handler/v1/health.go, api/user/registry/registry.go
* HealthCheckハンドラのコードリファクタ
* Registryのコードリファクタ
* Registryの分割の粒度
=> refactor: User APIのリファクタ

client/app/components/atoms/GranAlert.vue
- propsのvalidateの修正
無い
inはやっぱり動いてないっぽい
=> fix: validateの書き方を正しく修正

.env.sample, client/.envrc.sample, client/app/plugins/firebase.ts, client/app/plugins/vuetify.ts, client/nuxt.config.ts, docker-compose.yml
* docker-composeからfirebase関連の環境変数を追加できるように設定
* clientのfirebase関連の環境変数をリファクタ
* Vuetifyを次のバージョンに上げる際、nuxt.config.tsに書いておくとエラーになるので、アップデート前に対処
* Firebaseの環境変数周りをかなり修正したので、ローカルから起動できるかと、変数があっているか
* docker-composeから環境変数が追加できることは確認済み
docker-composeのenvを編集するついでにいくつか設定を編集しました。
レビューお願いします。
=> feature: Client 環境変数の設定

Makefile
=> refactor: makefileのコンテナ関連コマンドを修正

api/user/internal/interface/handler/README.md
=> docs: interfaceのドキュメント

doc/02_backend/01_development_rules/README.md, doc/02_backend/02_user_api/README.md
=> docs: backendのドキュメント

doc/01_frontend/01_development_rules/README.md, doc/02_backend/01_development_rules/README.md
=> docs: frontendのドキュメント

container/proxy/envoy.yaml
=> fix: /v1/usersでもアクセスできるように

client/lighthouserc.json, client/nuxt.config.ts
* Lighthouse CIの設定を編集
* 設定箇所あってるか
=> feature: Lighthouse CIの設定を編集

docker-compose.api.yml
=> feat: swaggerの追加

.env.sample, client/app/plugins/axios.ts, client/nuxt.config.ts, docker-compose.yml
* axiosの設定
* rootの.envに `API_URL` を追加
=> feat: axiosの設定

api/user/config/cors.go, api/user/config/router.go, api/user/go.mod, api/user/go.sum, container/proxy/envoy.yaml
* CORSの設定
* すまん、APIだけじゃなく、Envoy側も一箇所実装漏れがあった🙇‍♂️
* CORSの設定については、一旦全部OKにしてます!!
=> feature: CORSの設定

doc/02_backend/02_swagger/user_api.yaml
=> docs: swagger追記

client/lighthouserc.json
recommendedだと厳しいので消してみる
- lighthouseの設定変更
- ciの結果だけで！
- とりあえずプルリク出さないとactionが発火しないので設定はこれから追加するかも🙏
=> fix: lighthouseの設定変更

api/user/go.mod, api/user/go.sum, api/user/internal/infrastructure/persistence/group.go, api/user/internal/infrastructure/persistence/user.go, api/user/lib/firebase/firestore/client.go
* firebase用ライブラリを編集
* persistenceディレクトリのリファクタ
=> refactor: Firebase周りの編集

api/user/go.mod, api/user/go.sum, api/user/internal/domain/group.go, api/user/internal/domain/user.go, api/user/internal/infrastructure/persistence/group.go, api/user/internal/infrastructure/persistence/user.go, api/user/lib/firebase/firestore/client.go
* #396 の編集に伴うコード修正
* グループ作成時、ユーザーエンティティも更新
#396 の続き
=> Feature/user api/create group

client/app/assets/transitions.css, client/nuxt.config.ts
ページ遷移が滑らかになるようにアニメーションを追加
設定項目についてまだきちんと理解していないのでとりあえずという形
- cssのファイル名
=> feat: ページ遷移のアニメーション追加

api/group/config/router.go, api/group/internal/application/group.go, api/group/internal/application/response/group.go, api/group/internal/domain/repository/group.go, api/group/internal/domain/service/group.go, api/group/internal/infrastructure/persistence/group.go, api/group/internal/interface/handler/v1/group.go, doc/02_backend/02_swagger/group.api.yaml
=> feature: グループ一覧取得APIの実装

api/user/internal/application/user_test.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/service/user_test.go, api/user/internal/infrastructure/validation/user_test.go
=> faeture: Userサービスにテストを追加

client/package.json, client/spec/components/atoms/GranButton.spec.ts, client/spec/components/atoms/GranCard.spec.ts, client/spec/components/atoms/GranTextField.spec.ts, client/spec/helpers/component-helper.ts, client/spec/helpers/response/auth.ts, client/spec/helpers/response/index.ts, client/spec/helpers/store-helper.ts, client/spec/helpers/store/auth.ts, client/spec/helpers/store/index.ts, client/spec/store/auth.spec.ts, client/yarn.lock
* jestを用いたテストの実装
* サンプルがてら4ファイル分テストを実装しただけなので、残りの箇所も要実装
* テストの実装箇所は以下のとこに絞った
* components/**/*
* store/**/*
=> test: Jestのテスト設定とテストコードのサンプル実装

client/app/types/form/auth/login.ts, client/jest.config.js, client/spec/components/atoms/GranButton.spec.ts, client/spec/components/atoms/GranCard.spec.ts, client/spec/components/atoms/GranTextField.spec.ts, client/spec/helpers/component-helper.ts, client/spec/pages/signup.spec.ts
* Pagesのテストを追加
* テストの型周りの修正
* firebaseに関連する部分のテスト考えてない
=> test: Pagesのテストを追加とテストの型周り修正

api/group/config/router.go, api/group/internal/application/group.go, api/group/internal/domain/repository/group.go, api/group/internal/domain/service/group.go, api/group/internal/infrastructure/persistence/group.go, api/group/internal/interface/handler/v1/group.go
=> feature: グループ詳細取得APIの実装

api/group/internal/infrastructure/persistence/group.go
=> fix: ユーザリファレンス取得メソッドの修正

api/group/config/router.go, api/group/internal/application/group.go, api/group/internal/application/request/group.go, api/group/internal/application/validation/group.go, api/group/internal/domain/repository/group.go, api/group/internal/domain/service/group.go, api/group/internal/infrastructure/persistence/group.go, api/group/internal/interface/handler/v1/group.go, doc/02_backend/02_swagger/group.api.yaml
=> feature: グループ編集APIの実装

api/user/internal/interface/handler/v1/user.go
=> feat: 変数の定義箇所

api/group/internal/application/group.go
=> fix: グループにUserIDが含まれてるかの検証箇所修正

api/group/config/router.go, api/group/internal/application/group.go, api/group/internal/application/group_test.go, api/group/internal/domain/service/group.go, api/group/internal/domain/service/group_test.go, api/group/internal/interface/handler/v1/group.go, doc/02_backend/02_swagger/group.api.yaml
=> feature: グループ参加APIの実装

client/app/components/atoms/GranAvatar.vue, client/app/components/molecules/GranGroupNewForm.vue, client/app/components/templates/GranBoardNew.vue, client/app/pages/boads/new.vue, client/app/types/form/auth/group.ts, client/app/types/form/auth/index.ts, client/app/types/index.ts
groupに関して、typescriptを適用
- validate
- 型の定義
=> [group]: typescriptの適用

api/todo/config/router.go, api/todo/internal/application/board.go, api/todo/internal/application/board_test.go, api/todo/internal/application/response/board.go, api/todo/internal/domain/board.go, api/todo/internal/domain/repository/board.go, api/todo/internal/domain/service/board.go, api/todo/internal/domain/service/board_test.go, api/todo/internal/infrastructure/persistence/board.go, api/todo/internal/interface/handler/v1/board.go
* ボード一覧取得APIの実装
* スペルミス等
* 不要なコードの有無 (コメント等)
* 変数・関数の命名
=> feature: ボード一覧取得APIの実装

api/group/lib/firebase/authentication/client.go, api/todo/lib/firebase/authentication/client.go, api/user/lib/firebase/authentication/client.go
=> fix: ユーザ登録時にメールが送られないバグを修正

.env.sample, api/todo/.envrc.sample, api/todo/cmd/main.go, api/todo/config/environment.go, api/todo/go.mod, api/todo/lib/firebase/storage/client.go, api/todo/registry/registry.go, docker-compose.api.yml, docker-compose.yml
* lib配下にCloud Storageにファイルをアップロードするメソッドを追加
* サムネアップロードが必要な箇所のコードを変更
* user_api, group_apiにもライブラリを追加
* .envにバケット名追加
=> feature: Cloud Storage操作用のライブラリをsakusei

.github/workflows/cd-cilent.yml, .github/workflows/ci-client.yml
=> feat: clientのcd設定

.github/workflows/cd-user-api-for-staging.yml, container/api/group/Dockerfile.production, container/api/todo/Dockerfile.production, container/api/user/Dockerfile.production, doc/03_infrastructure/02_container/README.md
=> feature: 本番環境用 APIのコンテナイメージを作成

.env.sample, Makefile, container/terraform/Dockerfile, docker-compose.yml, terraform/.gitignore, terraform/Makefile, terraform/env/stg/backend.tf.sample, terraform/env/stg/main.tf, terraform/env/stg/outputs.tf, terraform/env/stg/terraform.tfvars.sample, terraform/env/stg/variables.tf, terraform/modules/gke-cluster.tf, terraform/modules/gke-node.tf, terraform/modules/outputs.tf, terraform/modules/variables.tf
* Terraformのコンテナ環境の構築
* Terraformの初期設定
* Terraformが正しく実行できることの確認
* 次のプルリクで実装予定
* Github Actionsの活用
* GKEの詳細設計
* Cloud DNSのコード化
=> feature: Terraformの初期設定

terraform/env/stg/main.tf, terraform/modules/gke-node.tf, terraform/modules/variables.tf
=> feat: ディスク容量の変更

client/app/components/organisms/GranGroupList.vue
=> [UI/UX]グループのタイトルと説明の実装

api/group/cmd/main.go, api/group/config/environment.go, api/group/go.mod, api/group/lib/firebase/storage/client.go, api/group/registry/registry.go, api/todo/cmd/main.go, api/user/cmd/main.go, api/user/config/environment.go, api/user/registry/registry.go, docker-compose.api.yml
* Cloud Storage操作用のライブラリの設定
* 特になし
=> feature: Cloud Storageの設定

api/todo/internal/domain/board.go, api/todo/internal/domain/task.go
* カンバン機能を作る上で必要となるエンティティの追加
* フィールド名
* フィールドの過不足
さっきやまゆーと話してたタスク一覧に最低限必要な値
* タスクID
* タスク名
* ラベル
以外も含めたもの(最終的に必要となる値全て含んだもの)で実装してあります。
=>  feature: エンティティの追加

api/todo/internal/domain/board.go, api/todo/internal/domain/repository/board.go, api/todo/internal/domain/service/board.go, api/todo/internal/domain/service/board_test.go, api/todo/internal/infrastructure/persistence/board.go, api/todo/internal/interface/handler/v1/board.go, api/todo/mock/domain/repository/board.go
=> feature: ボード詳細取得APIの編集

api/todo/config/router.go, api/todo/go.mod, api/todo/internal/application/board.go, api/todo/internal/application/board_test.go, api/todo/internal/application/request/board.go, api/todo/internal/application/task.go, api/todo/internal/application/task_test.go, api/todo/internal/application/validation/board.go, api/todo/internal/domain/error.go, api/todo/internal/domain/repository/board.go, api/todo/internal/domain/service/board.go, api/todo/internal/domain/service/board_test.go, api/todo/internal/domain/service/task.go, api/todo/internal/domain/service/task_test.go, api/todo/internal/infrastructure/persistence/board.go, api/todo/internal/interface/handler/error.go, api/todo/internal/interface/handler/v1/board.go, api/todo/mock/application/validation/board.go, api/todo/mock/domain/repository/board.go, api/todo/mock/domain/service/board.go, api/todo/mock/domain/service/task.go, api/todo/registry/task.go, docs/02_backend/02_swagger/todo_api.yaml
* カンバン編集機能(リスト、タスクの順序変更)APIの実装
=> feature: カンバン編集機能の実装

api/user/.golangci.yml, api/user/internal/application/user_test.go, api/user/internal/application/validation/base.go, api/user/internal/application/validation/user_test.go, api/user/internal/domain/service/user_test.go, api/user/internal/infrastructure/validation/user_test.go
=> Refactor/user api/test

api/group/.golangci.yml, api/group/internal/application/group.go, api/group/internal/application/group_test.go, api/group/internal/application/validation/base.go, api/group/internal/application/validation/group_test.go, api/group/internal/domain/service/group.go, api/group/internal/domain/service/group_test.go, api/group/internal/domain/service/user_test.go, api/group/internal/infrastructure/validation/group_test.go, api/group/mock/domain/service/group.go
=> refactor: test for group_api

api/todo/.golangci.yml, api/todo/internal/application/board.go, api/todo/internal/application/board_test.go, api/todo/internal/application/task_test.go, api/todo/internal/application/validation/base.go, api/todo/internal/application/validation/board_test.go, api/todo/internal/application/validation/task_test.go, api/todo/internal/domain/service/board_test.go, api/todo/internal/domain/service/task_test.go, api/todo/internal/domain/service/user_test.go, api/todo/internal/infrastructure/validation/board_test.go, api/todo/internal/infrastructure/validation/task_test.go
=> refactor: test for todo_api

api/todo/config/router.go, api/todo/internal/application/board.go, api/todo/internal/application/request/board.go, api/todo/internal/application/validation/board.go, api/todo/internal/domain/repository/task.go, api/todo/internal/domain/service/board.go, api/todo/internal/domain/service/board_test.go, api/todo/internal/domain/task.go, api/todo/internal/infrastructure/persistence/task.go, api/todo/internal/interface/handler/v1/board.go, api/todo/mock/application/validation/board.go, api/todo/mock/domain/repository/task.go, api/todo/mock/domain/service/board.go, docs/02_backend/02_swagger/todo_api.yaml
* ボードリスト編集APIの実装
* ボード詳細APIの修正
* ボードリスト編集APIのテスト作成
=> feature: ボードリスト編集APIの実装

api/todo/internal/application/board_test.go, api/todo/internal/application/validation/board_test.go, api/todo/internal/domain/service/board_test.go
=> feature: ボードリスト編集APIのテスト作成

api/user/config/router.go, api/user/internal/application/response/user.go, api/user/internal/application/user.go, api/user/internal/application/user_test.go, api/user/internal/interface/handler/v1/user.go, docs/02_backend/02_swagger/user_api.yaml
=> feature: プロフィール取得APIの実装

api/group/internal/application/response/group.go, api/group/lib/firebase/authentication/client.go, api/todo/lib/firebase/authentication/client.go, docs/02_backend/02_swagger/group_api.yaml, docs/02_backend/02_swagger/todo_api.yaml, docs/02_backend/02_swagger/user_api.yaml
* Swaggerの更新
* APIのレスポンス、一部修正
* Firebaseライブラリの編集
=> docs: Swaggerの更新

api/todo/config/router.go, api/todo/internal/application/response/task.go, api/todo/internal/application/task.go, api/todo/internal/application/task_test.go, api/todo/internal/domain/error.go, api/todo/internal/domain/repository/task.go, api/todo/internal/domain/service/task.go, api/todo/internal/domain/service/task_test.go, api/todo/internal/domain/task.go, api/todo/internal/infrastructure/persistence/task.go, api/todo/internal/interface/handler/v1/task.go, api/todo/mock/domain/repository/task.go, api/todo/mock/domain/service/task.go, docs/02_backend/02_swagger/todo_api.yaml
=> feature: タスク詳細取得APIの実装

api/group/internal/application/response/error.go, api/group/internal/domain/error.go, api/group/internal/interface/handler/error.go, api/todo/internal/application/response/error.go, api/todo/internal/interface/handler/error.go, api/user/internal/application/response/error.go, api/user/internal/domain/error.go, api/user/internal/interface/handler/error.go
* エラーコードを各サービス間で揃える
* エラー処理をアプリケーション層に寄せたい
=> refactor: error handling

.github/workflows/ci-client-reviewdog.yml, .github/workflows/ci-group-api-reviewdog.yml, .github/workflows/ci-todo-api-reviewdog.yml, .github/workflows/ci-user-api-reviewdog.yml, api/group/Makefile, api/todo/Makefile, api/user/Makefile, client/README.md
=> feat: Setup reviewdog for user api

api/user/lib/firebase/authentication/client.go, client/app/components/templates/GranAccountEdit.vue, client/app/pages/account/edit.vue, client/app/store/account.ts, client/app/types/form/auth/account.ts, client/yarn.lock
=> 入力値をuser変更apiに渡す
